swagger: '2.0'
info:
  title: JTracker Workflow Registration Service API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
#security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
#  - oauth2: [uid]
paths:
  #/workflows:
  #  get:
  #    tags: [Workflows]
  #    operationId: app.get_all_workflows
  #    summary: Get all workflows (not implemented yet)
  #    responses:
  #      200:
  #        description: Return list of workflows
  #        schema:
  #          type: array
  /workflows/id/{workflow_id}:
    get:
      tags: [Workflows]
      operationId: app.get_workflow_by_id
      summary: Get workflow by workflow ID
      parameters:
        - $ref: '#/parameters/workflow_id'
      responses:
        200:
          description: Return workflow
          schema:
            type: object
  /workflows/id/{workflow_id}/ver/{workflow_version}:
    get:
      tags: [Workflows]
      operationId: app.get_workflow_by_id_and_version
      summary: Get workflow by workflow ID and version
      parameters:
        - $ref: '#/parameters/workflow_id'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Return workflow
          schema:
            type: object
  /workflows/owner/{owner_name}:
    get:
      tags: [Workflows]
      operationId: app.get_workflows
      summary: Get all workflows for an owner
      parameters:
        - $ref: '#/parameters/owner_name'
      responses:
        200:
          description: Return workflows
          schema:
            type: array
    post:
      tags: [Workflows]
      operationId: app.register_workflow
      summary: Register a new workflow under an owner
      parameters:
        - $ref: '#/parameters/owner_name'
        - name: workflow_entry
          in: body
          schema:
            $ref: '#/definitions/WorkflowEntry'
      responses:
        200:
          description: Workflow created
        409:
          description: Workflow registration failed
  #/workflows/owner/{owner_name}/workflow/{workflow_name}/teams:
  #  get:
  #  post:
  #/workflows/owner/{owner_name}/workflow/{workflow_name}/team/{team_name}:
  #  get:
  #  delete:
  /workflows/owner/{owner_name}/workflow/{workflow_name}:
    get:
      tags: [Workflows]
      operationId: app.get_workflow
      summary: Get detail for a workflow (including all versions)
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
      responses:
        200:
          description: Return workflow
    delete:
      tags: [Workflows]
      operationId: app.delete_workflow1
      summary: Delete an unpublished workflow entry (not implemented yet)
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
      responses:
        200:
          description: Deletion performed
        400:
          description: Unable to delete
  /workflows/owner/{owner_name}/workflow/{workflow_name}/ver/{workflow_version}:
    get:
      tags: [Workflows]
      operationId: app.get_workflow_ver
      summary: Get detail for a workflow with specific version
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Return workflow
          schema:
            type: object
        404:
          description: Owner does not exist
    delete:
      tags: [Workflows]
      operationId: app.delete_workflow
      summary: Delete an unpublished version of a workflow (not implemented yet)
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Deletion performed
        400:
          description: Unable to delete
  /workflows/owner/{owner_name}/workflow/{workflow_name}/ver/{workflow_version}/release:
    put:
      tags: [Workflows]
      operationId: app.release_workflow
      summary: Release a workflow, no change is permitted once released (not implemented yet)
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Return workflows
  /workflows/owner/{owner_name}/workflow/{workflow_name}/ver/{workflow_version}/workflow_file:
    get:
      tags: [Workflows]
      operationId: app.download_workflowfile
      summary: Download workflowfile for a particular version of a workflow
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Workflow file downloaded
  /workflows/owner/{owner_name}/workflow/{workflow_name}/ver/{workflow_version}/workflow_package:
    get:
      tags: [Workflows]
      operationId: app.download_workflow_package
      summary: Download workflow package for a particular version of a workflow (not implemented yet)
      produces:
        - "application/octet-stream"
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Workflow package downloaded
          schema:
            type: file
  /workflows/owner/{owner_name}/workflow/{workflow_name}/ver/{workflow_version}/job_json_template:
    get:
      tags: [JobJSON]
      operationId: app.get_job_json_template
      summary: Retrieve JobJSON template for a particular version of a workflow (not implemented yet)
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: JobJSON template returned
  /workflows/owner/{owner_name}/workflow/{workflow_name}/ver/{workflow_version}/job_execution_plan:
    put:
      tags: [JobJSON]
      operationId: app.get_execution_plan
      summary: Generate a job execution plan for the supplied JobJSON against a particular version of a workflow
      parameters:
        - $ref: '#/parameters/owner_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
        - name: job_json
          in: body
          required: true
          schema:
            $ref: '#/definitions/JobJSON'
      responses:
        200:
          description: Job execution plan generated
        400:
          description: JobJSON invalid


parameters:
  owner_name:
    name: owner_name
    description: Owner's unique name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z]{1}[a-zA-Z0-9-_]{2,31}$"
  workflow_id:
    name: workflow_id
    description: Workflow's unique ID
    in: path
    type: string
    required: true
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  workflow_name:
    name: workflow_name
    description: Workflow's name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z]{1}[a-zA-Z0-9-_]{2,31}$"
  workflow_version:
    name: workflow_version
    description: Workflow's version
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9]{1}[a-zA-Z0-9-_.]{1,15}$"

definitions:
  WorkflowEntry:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z]{1}[a-zA-Z0-9-_]{2,31}$"
        example: "webpage-word-count"
        minLength: 3
        maxLength: 30
      version:
        type: string
        description: Workflow's version
        pattern: "^[a-zA-Z0-9]{1}[a-zA-Z0-9-_.]{1,15}$"
        example: "0.0.6"
      git_server:
        type: string
        description: Git server
        example: "https://github.com"
      git_account:
        type: string
        description: Git account name
        example: "jthub"
      git_repo:
        type: string
        description: Git repository name
        pattern: "^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]{1,63}$"
        example: "demo-workflows"
      git_path:
        type: string
        description: Path in git repo to the workflow code
        example: "webpage-word-count"
      git_tag:
        type: string
        description: Git tag or commit
        pattern: "^[a-zA-Z0-9]{1}[a-zA-Z0-9-_.]{1,39}$"
        example: "webpage-word-count.0.0.6"
      workflow_type:
        type: string
        description: In which language workflow is written
        enum: ["JTracker"]
        example: "JTracker"
        readOnly: true
  JobJSON:
    type: object
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9]{1}[a-zA-Z0-9-_.]{2,63}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 64


securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
